# Generated by Django 4.0.4 on 2022-07-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='date began')),
                ('total_calories', models.IntegerField(default=0)),
                ('total_sleep', models.IntegerField(default=0)),
                ('total_chest', models.IntegerField(default=0)),
                ('total_shoulders', models.IntegerField(default=0)),
                ('total_triceps', models.IntegerField(default=0)),
                ('total_protein', models.IntegerField(default=0)),
                ('total_carbs', models.IntegerField(default=0)),
            ],
        ),
    ]
