# Generated by Django 4.0.4 on 2022-07-08 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutweek',
            name='start_date',
        ),
        migrations.AddField(
            model_name='workoutweek',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date ended'),
            preserve_default=False,
        ),
    ]
