# Generated by Django 4.0.4 on 2022-07-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_workoutweek_start_date_workoutweek_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutweek',
            name='bench_max',
            field=models.IntegerField(default=0),
        ),
    ]
